title: Stackbit Azimuth Theme
baseurl: /
permalink: '/:title/'
palette: blue
header:
  has_nav: true
  logo_img: /images/socialwave-blau-logo-1-.png
  menu:
    actions:
      - label: Sign Up
        url: /signup
  title: Azimuth
footer:
  content: '&copy; Socialwave GmbH. All rights reserved.'
  has_nav: true
  has_social: true
  has_subscribe: true
  links: []
  logo_img: /images/socialwave-weiss-logo-300x113.png
  nav_title: Company
  social_title: Community
  subscribe_content: Stay up to date with our latest developments.
  subscribe_title: Subscribe
  tagline: Socialwave GmbH
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
